# https://mise.jdx.dev/configuration.html
[settings]
activate_aggressive = true
jobs = 1

[tasks.check]
depends = ["prettier:check", "shellcheck", "shfmt:check"]
description = "Run code quality checks"

[tasks.format]
depends = ["prettier:format", "shfmt:format"]
description = "Run code formatters"

[tasks."prettier:check"]
description = "Check web code formatting with Prettier"
run = "prettier --check ."

[tasks."prettier:format"]
description = "Format web code with Prettier"
run = "prettier --write ."

[tasks.shellcheck]
description = "Check shell scripts with ShellCheck"
run = "shellcheck dovi_tool/entrypoint.sh"

[tasks."shfmt:check"]
description = "Check shell script formatting with shfmt"
run = "shfmt -d ."

[tasks."shfmt:format"]
description = "Format shell scripts with shfmt"
run = "shfmt -w ."

[tools]
# https://mise.jdx.dev/configuration.html#scopes
# https://mise.jdx.dev/dev-tools/
#
# registry tools from core backend
node = "24"
# registry tools from other backends
shellcheck = "prefix:0.11"
shfmt = "prefix:3.13"
# non-registry tools from specific backends
"npm:prettier" = "prefix:3"
